//
// Created by ruben on 29-9-18.
//

#ifndef SYSTEMSPROGRAMMING_PROTOCOL_H
#define SYSTEMSPROGRAMMING_PROTOCOL_H

extern const int CONTROL_FAIL_DATAFILE;
extern const int CONTROL_FAIL_LIBRARY;






#endif //SYSTEMSPROGRAMMING_PROTOCOL_H
